// <auto-generated />
namespace DATA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class v5131 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v5131));
        
        string IMigrationMetadata.Id
        {
            get { return "201811052254048_v5131"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
